apiVersion: v1
kind: Pod
metadata:
  name: go-service-pod
  labels:
    app: go-service-pod
    type: go-service
    env: dev
    version: alpha
spec:
  containers:
  - name: go-service-container1
    image: goservice:alpha
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "200Mi"
        cpu: "200m"
    ports:
    - containerPort: 8080
  - name: prism-proxy
    image: stoplight/prism:latest
    volumeMounts:
    - name: openapi-volume
      mountPath: /etc/prism
    args: ["proxy", "/etc/prism/petstore.yaml", "http://localhost:8080","--errors"]
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "200Mi"
        cpu: "200m"
    ports:
    - containerPort: 4010
  volumes:
  - name: openapi-volume
    configMap:
      name: openapi-specification

# -------------Resource Footprints------------------
#           CPU            Memory
# Go-Server <5m            <15Mi
# Prism     <10m           <150Mi
