apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  selector:
    app: go-service-pod   # This should match the labels of your pod
  ports:
    - protocol: TCP
      port: 8080           
      targetPort: 8080  
